name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    
    - name: Build
      run: cargo build --verbose
    
    - name: Run tests
      run: cargo test --verbose
    
    - name: Build for aarch64-unknown-linux-gnu
      run: |
        rustup target add aarch64-unknown-linux-gnu
        cargo build --release --target aarch64-unknown-linux-gnu
    
    - name: Upload aarch64 binary
      uses: actions/upload-artifact@v3
      with:
        name: focusbuddy-aarch64
        path: target/aarch64-unknown-linux-gnu/release/focusbuddy 