name: Cross-compilation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        target: [x86_64-unknown-linux-gnu, x86_64-pc-windows-msvc, x86_64-apple-darwin]

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          focusbuddy/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Add target
      run: rustup target add ${{ matrix.target }}

    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential pkg-config libssl-dev

    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        rustup target add x86_64-pc-windows-msvc

    - name: Setup project
      working-directory: focusbuddy
      run: |
        touch focusbuddy.json
        echo '{"focus_duration": 25, "break_duration": 5, "tasks": []}' > focusbuddy.json
        chmod 644 focusbuddy.json

    - name: Build
      working-directory: focusbuddy
      run: |
        cargo check --target ${{ matrix.target }}
        cargo build --release --target ${{ matrix.target }}
        cargo test --target ${{ matrix.target }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: focusbuddy-${{ matrix.target }}
        path: focusbuddy/target/${{ matrix.target }}/release/focusbuddy* 